packages:
  - packages/*
  - '!**/test/**'
  - '!**/__tests__/**'
  - examples/*
  - apps/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - agent-browser
  - esbuild
  - nx
  - sharp
  - sqlite3
  - unrs-resolver
