blank_issues_enabled: false
contact_links:
  - name: Slack channel
    url: https://join.slack.com/t/flatbreadworkspace/shared_invite/zt-1bvnhr38j-oHFun85aGfaNp9qwizOORw
    about: Ask questions and discuss with other Flatbread users in real time.
