import { GraphQLSchema } from 'graphql';

interface FlatbreadCache {
  schema: GraphQLSchema | null;
}

/**
 * A general cache for computationally heavy operations in Flatbread.
 */
export const cache: FlatbreadCache = {
  schema: null,
};

/**
 * Setter function for caching the GraphQL schema generated by Flatbread
 */
export function cacheSchema(schema: GraphQLSchema) {
  cache.schema = schema;
}
