name: Pipeline

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.15.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set an escape hatch exclusive to this monorepo
        id: escape_hatch
        run: |
          echo "FLATBREAD_CI=true" >> $GITHUB_ENV

      - run: pnpm i

      - name: Build
        run: pnpm build

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.15.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set an escape hatch exclusive to this monorepo
        id: escape_hatch
        run: |
          echo "FLATBREAD_CI=true" >> $GITHUB_ENV

      - run: pnpm i

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.15.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set an escape hatch exclusive to this monorepo
        id: escape_hatch
        run: |
          echo "FLATBREAD_CI=true" >> $GITHUB_ENV

      - run: pnpm i

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  integration-sveltekit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.15.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set an escape hatch exclusive to this monorepo
        id: escape_hatch
        run: |
          echo "FLATBREAD_CI=true" >> $GITHUB_ENV

      - run: pnpm i

      - name: Build SvelteKit Integration
        run: pnpm play:build

  integration-nextjs:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^9.15.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set an escape hatch exclusive to this monorepo
        id: escape_hatch
        run: |
          echo "FLATBREAD_CI=true" >> $GITHUB_ENV

      - run: pnpm i

      - name: Build Next.js integration
        # TODO: extract the Flatbread build to a separate job that this job can depend on
        run: pnpm build && cd examples/nextjs && pnpm build
